// <auto-generated />
using System;
using MaintenanceRequests.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MaintenanceRequests.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260930161640_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MaintenanceRequests.Domain.Requests.MaintenanceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssigneeId")
                        .HasColumnType("integer")
                        .HasColumnName("assignee_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<int>("RequesterId")
                        .HasColumnType("integer")
                        .HasColumnName("requester_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_maintenance_requests");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_maintenance_requests_title");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("ix_maintenance_requests_created_at_id");

                    b.HasIndex("Status", "CreatedAt", "Id")
                        .HasDatabaseName("ix_maintenance_requests_status_created_at_id");

                    b.ToTable("maintenance_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_maintenance_requests_category", "category IN ('Infrastructure', 'Equipment', 'Software', 'Other')");

                            t.HasCheckConstraint("ck_maintenance_requests_description_length", "char_length(description) BETWEEN 10 AND 2000");

                            t.HasCheckConstraint("ck_maintenance_requests_priority", "priority IN ('Low', 'Medium', 'High', 'Critical')");

                            t.HasCheckConstraint("ck_maintenance_requests_status", "status IN ('Pending', 'InProgress', 'OnHold', 'Resolved', 'Cancelled')");

                            t.HasCheckConstraint("ck_maintenance_requests_title_length", "char_length(title) BETWEEN 5 AND 120");
                        });
                });

            modelBuilder.Entity("MaintenanceRequests.Domain.Requests.RequestHistoryEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ActorId")
                        .HasColumnType("integer")
                        .HasColumnName("actor_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("from_status");

                    b.Property<int?>("NewAssigneeId")
                        .HasColumnType("integer")
                        .HasColumnName("new_assignee_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int?>("PreviousAssigneeId")
                        .HasColumnType("integer")
                        .HasColumnName("previous_assignee_id");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer")
                        .HasColumnName("request_id");

                    b.Property<string>("ToStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_request_history");

                    b.HasIndex("RequestId", "OccurredAt", "Id")
                        .HasDatabaseName("ix_request_history_request_id_occurred_at_id");

                    b.ToTable("request_history", null, t =>
                        {
                            t.HasCheckConstraint("ck_request_history_consistency", "(type = 'Created' AND to_status IS NOT NULL) OR (type = 'StatusChanged' AND from_status IS NOT NULL AND to_status IS NOT NULL) OR (type = 'AssigneeChanged' AND new_assignee_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_request_history_from_status", "from_status IN ('Pending', 'InProgress', 'OnHold', 'Resolved', 'Cancelled')");

                            t.HasCheckConstraint("ck_request_history_to_status", "to_status IN ('Pending', 'InProgress', 'OnHold', 'Resolved', 'Cancelled')");

                            t.HasCheckConstraint("ck_request_history_type", "type IN ('Created', 'StatusChanged', 'AssigneeChanged')");
                        });
                });

            modelBuilder.Entity("MaintenanceRequests.Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ana Gómez"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Carlos Ruiz"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Laura Martínez"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Andrés López"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sofía Herrera"
                        });
                });

            modelBuilder.Entity("MaintenanceRequests.Domain.Requests.MaintenanceRequest", b =>
                {
                    b.HasOne("MaintenanceRequests.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_maintenance_requests_users_assignee_id");

                    b.HasOne("MaintenanceRequests.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_requests_users_requester_id");
                });

            modelBuilder.Entity("MaintenanceRequests.Domain.Requests.RequestHistoryEntry", b =>
                {
                    b.HasOne("MaintenanceRequests.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_request_history_users_actor_id");

                    b.HasOne("MaintenanceRequests.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("NewAssigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_request_history_users_new_assignee_id");

                    b.HasOne("MaintenanceRequests.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("PreviousAssigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_request_history_users_previous_assignee_id");

                    b.HasOne("MaintenanceRequests.Domain.Requests.MaintenanceRequest", null)
                        .WithMany("History")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_request_history_maintenance_requests_request_id");
                });

            modelBuilder.Entity("MaintenanceRequests.Domain.Requests.MaintenanceRequest", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
